### PR TITLE
#26 Add travis scripts to ci-templates folder

### PR DESCRIPTION
**Pull request by jortizsao**
Add the CI scripts in the ci-templates subfolder in order to generalize the necessary scripts for building/deploying in k8s.

The idea is that these scripts could be pulled from any particular project

### CODE REVIEW

**Comment by butenkor** [comment]
Maybe it makes sense to put those files into dedicated travis subfolder as for circle CI for example one could use preconfigured docker image which has all required dependencies already installed?

**Comment by jortizsao** [comment]
@butenkor ok, I move them to _travis-templates_ subfolder

**Comment by butenkor** [comment]
Maybe something like that:

```
ci-templates
  |-- travis-ci
  |-- circle-ci
  |-- jenkins
```

**Comment by jortizsao** [comment]
ok, I'll do it

**Comment by svenmueller** [comment]
The CI scripts are very specific to the commercetools usecase and are bound to GCP provider. I'm not sure if they should be part of this open-source k8s chart repository.

**Comment by heshamMassoud** [comment]
Also these scripts need some prerequisites and some conventions (directory structure, naming, etc..) in order to work correctly. You can find them in the README of where the scripts existed before. I think we should have them added in a README in the scripts directory also.

I agree with @svenmueller that it's very specific to the commercetools usecase. So maybe it's ok if we specify in the README of the scripts dir for example in the `ci-templates/travis` that this is an "example of how to use the charts in the repo in deploying your charts"? WDYT?

**Comment by butenkor** [comment]
@svenmueller Yes, we need to generalise them. For now we wanted to share them between different project instead of copy & pasting everywhere. Lets start with that and generalise step by step. And yes, we should mark them as template examples. They are not mandatory for charts usage. Not sure if creating dedicated repository would do any better here.

**Comment by svenmueller** [comment]
How about adding a README and a sample `travis.yml` to explain how the scripts can be used. IMHO, the scripts alone are not very useful. I also noticed that the scripts (e.g. `gcloud-login.sh`) seem to be bound to TravisCI. I would like to see something like this:

```
ci-examples/
  travis-gke/
    README.md
    .travis.yml
    scripts/
      script.sh
      ...
```

- `ci-examples/travis-gke/README.md`: provides all required information how to use scripts, prerequisites etc.
- `ci-examples/travis-gke/.travis.yml`: simple travis build script example

**Comment by jortizsao** [comment]
Ok, so it seems that @svenmueller structure is the one we all agree with. I move forward with it

**Comment by butenkor** [comment]
To avoid copying files from project to project why not add `crypt` file here too?

**Comment by jortizsao** [comment]
@butenkor encrypt.sh added and README.md updated accordingly

**Review by butenkor — APPROVED** [review]
Thanks!

**Pull request merged**
